### ISSUE TITLE
Readd Visual Testing 

### ISSUE THREAD

**Issue by azizhk** [saas-bn/pebble#248]
Visual Testing using https://www.chromaticqa.com/ have been disabled.
Need to add them back so that issues like https://github.com/anarock/pebble/pull/247 can be caught before merge.

**Comment by ritz078** [comment]
why is it disabled ?

**Comment by azizhk** [comment]
I don't know. It looks like its disabled because it is not sending checks on commits.
I don't the account access on chromaticqa. Was going to ask @akki91 who has it.
Don't know if this was disabled with monorepo setup.

**Comment by akki91** [comment]
Never created any such account or maybe I don't remember

**Comment by azizhk** [comment]
https://docs.chromaticqa.com/open-source
@akki91 are you creating an account using buggy-bot or developer at anarock.com?
Or shall I create a new account?

**Comment by ChaitanyaGadodia** [comment]
@dxtr026 can you create an account using developer@anarock.com?

**Comment by dxtr026** [comment]
@ChaitanyaGadodia  this is done cc: @ritz078  @azizhk
